# ===================================================================
# CONFIGURACIÓN DE DESARROLLO (Tu máquina local)
# ===================================================================
spring:
  datasource:
    # ¿Por qué lo ponemos así?
    # Apunta directamente al contenedor de PostgreSQL que tienes corriendo en tu localhost. 
    # Aquí es totalmente seguro escribir el usuario y contraseña 'admin/admin' en texto plano, 
    # porque esta base de datos solo existe en tu entorno de desarrollo local.
    url: jdbc:postgresql://localhost:5432/smartlogistics
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    # Mantenemos 'validate' porque en desarrollo las tablas las sigue gestionando Flyway
    hibernate:
      ddl-auto: validate
    # ¿Por qué true? 
    # En desarrollo NECESITAMOS ver las sentencias SQL que genera Hibernate en la consola 
    # para depurar fallos, comprobar que los mapeos @Entity funcionan y optimizar consultas.
    show-sql: true
    properties:
      hibernate:
        format_sql: true # Formatea el SQL para que sea legible en tu terminal

# CONFIGURACIÓN DE SEGURIDAD LOCAL (JWT)
jwt:
  # ¿Por qué dejamos la clave aquí escrita?
  # En desarrollo es cómodo tener una clave harcodeada compartida para que el equipo 
  # pueda levantar el proyecto sin configurar nada más. Al ser un entorno local, 
  # no hay peligro de que nadie nos robe el secreto.
  secret: V2F5QmV5b25kQVNlY3VyZUtleVRoYXQxczI1NkJpdHNMME5H
  expiration: 86400000 # 24 horas en milisegundos