version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: smartlogistics-postgres
    environment:
      POSTGRES_DB: smartlogistics
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    container_name: smartlogistics-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: smartlogistics-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/smartlogistics
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HOTNAME: localhost
      KC_HOSTNAME_PORT: 9090
      KC_HTTP_RELATIVE_PATH: /auth
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: